// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using db_portafolio;

#nullable disable

namespace db_portafolio.Migrations
{
    [DbContext(typeof(PortafolioContext))]
    [Migration("20231110190244_InitDB")]
    partial class InitDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("db_portafolio.PF_Language", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("url_img")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("id");

                    b.ToTable("pf_language", (string)null);
                });

            modelBuilder.Entity("db_portafolio.PF_Link", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<bool>("estado")
                        .HasColumnType("bit");

                    b.Property<int>("id_link_grp")
                        .HasColumnType("int");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("url_link")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("id");

                    b.HasIndex("id_link_grp");

                    b.ToTable("pf_link", (string)null);
                });

            modelBuilder.Entity("db_portafolio.PF_Link_Grp", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<bool>("estado")
                        .HasColumnType("bit");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("id");

                    b.ToTable("pf_link_grp", (string)null);
                });

            modelBuilder.Entity("db_portafolio.PF_Pro_Lang", b =>
                {
                    b.Property<int>("id_project")
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    b.Property<int>("id_language")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.HasKey("id_project", "id_language");

                    b.HasIndex("id_language");

                    b.ToTable("pf_pro_lang", (string)null);
                });

            modelBuilder.Entity("db_portafolio.PF_Pro_Prol", b =>
                {
                    b.Property<int>("id_project")
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    b.Property<int>("id_project_list")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.HasKey("id_project", "id_project_list");

                    b.HasIndex("id_project_list");

                    b.ToTable("pf_pro_prol", (string)null);
                });

            modelBuilder.Entity("db_portafolio.PF_Pro_Tech", b =>
                {
                    b.Property<int>("id_project")
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    b.Property<int>("id_technology")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.HasKey("id_project", "id_technology");

                    b.HasIndex("id_technology");

                    b.ToTable("pf_pro_tech", (string)null);
                });

            modelBuilder.Entity("db_portafolio.PF_Project", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("orden")
                        .HasColumnType("int");

                    b.Property<string>("url_img")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("id");

                    b.ToTable("pf_project", (string)null);
                });

            modelBuilder.Entity("db_portafolio.PF_Project_List", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("url_deploy")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("url_repo")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("id");

                    b.ToTable("pf_project_list", (string)null);
                });

            modelBuilder.Entity("db_portafolio.PF_Technology", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("url_img")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("id");

                    b.ToTable("pf_technology", (string)null);
                });

            modelBuilder.Entity("db_portafolio.PF_Link", b =>
                {
                    b.HasOne("db_portafolio.PF_Link_Grp", "LinksGrp")
                        .WithMany("Links")
                        .HasForeignKey("id_link_grp")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LinksGrp");
                });

            modelBuilder.Entity("db_portafolio.PF_Pro_Lang", b =>
                {
                    b.HasOne("db_portafolio.PF_Language", "Language")
                        .WithMany()
                        .HasForeignKey("id_language")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("db_portafolio.PF_Project", "Project")
                        .WithMany()
                        .HasForeignKey("id_project")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("db_portafolio.PF_Pro_Prol", b =>
                {
                    b.HasOne("db_portafolio.PF_Project", "Project")
                        .WithMany()
                        .HasForeignKey("id_project")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("db_portafolio.PF_Project_List", "ProjectList")
                        .WithMany()
                        .HasForeignKey("id_project_list")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("ProjectList");
                });

            modelBuilder.Entity("db_portafolio.PF_Pro_Tech", b =>
                {
                    b.HasOne("db_portafolio.PF_Project", "Project")
                        .WithMany()
                        .HasForeignKey("id_project")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("db_portafolio.PF_Technology", "Technology")
                        .WithMany()
                        .HasForeignKey("id_technology")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("Technology");
                });

            modelBuilder.Entity("db_portafolio.PF_Link_Grp", b =>
                {
                    b.Navigation("Links");
                });
#pragma warning restore 612, 618
        }
    }
}
