// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using db_portafolio;

#nullable disable

namespace db_portafolio.Migrations
{
    [DbContext(typeof(PortafolioContext))]
    partial class PortafolioContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("db_portafolio.PF_Language", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("url_img")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("id");

                    b.ToTable("pf_pro_language", (string)null);

                    b.HasData(
                        new
                        {
                            id = 1,
                            nombre = "C#",
                            url_img = "pf_csharp.svg"
                        },
                        new
                        {
                            id = 2,
                            nombre = "CSS",
                            url_img = "pf_css.svg"
                        },
                        new
                        {
                            id = 3,
                            nombre = "HTML",
                            url_img = "pf_html.svg"
                        },
                        new
                        {
                            id = 4,
                            nombre = "JavaScript",
                            url_img = "pf_js.svg"
                        },
                        new
                        {
                            id = 5,
                            nombre = "VisualBasic",
                            url_img = "pf_vb.svg"
                        },
                        new
                        {
                            id = 6,
                            nombre = "Python",
                            url_img = "pf_py.svg"
                        },
                        new
                        {
                            id = 7,
                            nombre = "TypeScript",
                            url_img = "pf_ts.svg"
                        });
                });

            modelBuilder.Entity("db_portafolio.PF_Link", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<bool>("estado")
                        .HasColumnType("bit");

                    b.Property<int>("id_link_grp")
                        .HasColumnType("int");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("url_link")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("id");

                    b.HasIndex("id_link_grp");

                    b.ToTable("pf_link", (string)null);

                    b.HasData(
                        new
                        {
                            id = 1,
                            estado = true,
                            id_link_grp = 1,
                            nombre = "Strapi",
                            url_link = "https://strapi.io"
                        },
                        new
                        {
                            id = 2,
                            estado = true,
                            id_link_grp = 1,
                            nombre = "Mui",
                            url_link = "https://mui.com"
                        },
                        new
                        {
                            id = 3,
                            estado = true,
                            id_link_grp = 1,
                            nombre = "Tailwindcss",
                            url_link = "https://tailwindcss.com"
                        },
                        new
                        {
                            id = 4,
                            estado = true,
                            id_link_grp = 1,
                            nombre = "DaisyUI",
                            url_link = "https://daisyui.com"
                        },
                        new
                        {
                            id = 5,
                            estado = true,
                            id_link_grp = 1,
                            nombre = "NextJS",
                            url_link = "https://nextjs.org"
                        },
                        new
                        {
                            id = 6,
                            estado = true,
                            id_link_grp = 1,
                            nombre = "NextUI",
                            url_link = "https://nextui.org"
                        },
                        new
                        {
                            id = 7,
                            estado = true,
                            id_link_grp = 1,
                            nombre = "NextAuth",
                            url_link = "https://next-auth.js.org"
                        },
                        new
                        {
                            id = 8,
                            estado = true,
                            id_link_grp = 1,
                            nombre = "FastAPI",
                            url_link = "https://fastapi.tiangolo.com"
                        },
                        new
                        {
                            id = 9,
                            estado = true,
                            id_link_grp = 1,
                            nombre = "Tremor",
                            url_link = "https://www.tremor.so"
                        },
                        new
                        {
                            id = 10,
                            estado = true,
                            id_link_grp = 1,
                            nombre = "Heroicons",
                            url_link = "https://heroicons.com"
                        },
                        new
                        {
                            id = 11,
                            estado = true,
                            id_link_grp = 2,
                            nombre = "CodeDex",
                            url_link = "https://www.w3schools.com"
                        },
                        new
                        {
                            id = 12,
                            estado = true,
                            id_link_grp = 2,
                            nombre = "w3schools",
                            url_link = "https://www.w3schools.com"
                        },
                        new
                        {
                            id = 13,
                            estado = true,
                            id_link_grp = 2,
                            nombre = "Scrimba",
                            url_link = "https://scrimba.com"
                        },
                        new
                        {
                            id = 14,
                            estado = true,
                            id_link_grp = 2,
                            nombre = "Animate",
                            url_link = "https://animate.style"
                        },
                        new
                        {
                            id = 15,
                            estado = true,
                            id_link_grp = 2,
                            nombre = "CodelyTV",
                            url_link = "https://www.youtube.com/@CodelyTV"
                        },
                        new
                        {
                            id = 16,
                            estado = true,
                            id_link_grp = 2,
                            nombre = "LucidChart",
                            url_link = "https://www.lucidchart.com"
                        },
                        new
                        {
                            id = 17,
                            estado = true,
                            id_link_grp = 2,
                            nombre = "Uiverse",
                            url_link = "https://uiverse.io/all"
                        },
                        new
                        {
                            id = 18,
                            estado = true,
                            id_link_grp = 2,
                            nombre = "DevDocs",
                            url_link = "https://devdocs.io"
                        },
                        new
                        {
                            id = 19,
                            estado = true,
                            id_link_grp = 2,
                            nombre = "WebDev",
                            url_link = "https://web.dev"
                        },
                        new
                        {
                            id = 20,
                            estado = true,
                            id_link_grp = 3,
                            nombre = "Railway",
                            url_link = "https://railway.app"
                        },
                        new
                        {
                            id = 21,
                            estado = true,
                            id_link_grp = 3,
                            nombre = "Netlify",
                            url_link = "https://www.netlify.com"
                        },
                        new
                        {
                            id = 22,
                            estado = true,
                            id_link_grp = 3,
                            nombre = "Vercel",
                            url_link = "https://vercel.com"
                        },
                        new
                        {
                            id = 23,
                            estado = true,
                            id_link_grp = 3,
                            nombre = "FreeAspHosting",
                            url_link = "https://freeasphosting.net"
                        },
                        new
                        {
                            id = 24,
                            estado = true,
                            id_link_grp = 3,
                            nombre = "InfinityFree",
                            url_link = "https://www.infinityfree.net"
                        },
                        new
                        {
                            id = 25,
                            estado = true,
                            id_link_grp = 3,
                            nombre = "AzureDevObs",
                            url_link = "https://dev.azure.com"
                        },
                        new
                        {
                            id = 26,
                            estado = true,
                            id_link_grp = 3,
                            nombre = "DigitalOcean",
                            url_link = "https://www.digitalocean.com"
                        },
                        new
                        {
                            id = 27,
                            estado = true,
                            id_link_grp = 3,
                            nombre = "Linode",
                            url_link = "https://www.linode.com/es"
                        },
                        new
                        {
                            id = 28,
                            estado = true,
                            id_link_grp = 3,
                            nombre = "DonWeb",
                            url_link = "https://donweb.com/es-cl"
                        },
                        new
                        {
                            id = 29,
                            estado = true,
                            id_link_grp = 3,
                            nombre = "Heroku",
                            url_link = "https://www.heroku.com"
                        },
                        new
                        {
                            id = 30,
                            estado = true,
                            id_link_grp = 4,
                            nombre = "PixaBay",
                            url_link = "https://pixabay.com"
                        },
                        new
                        {
                            id = 31,
                            estado = true,
                            id_link_grp = 4,
                            nombre = "FreePik",
                            url_link = "https://www.freepik.com"
                        },
                        new
                        {
                            id = 32,
                            estado = true,
                            id_link_grp = 4,
                            nombre = "UnSplash",
                            url_link = "https://unsplash.com"
                        },
                        new
                        {
                            id = 33,
                            estado = true,
                            id_link_grp = 4,
                            nombre = "FreeSVG",
                            url_link = "https://freesvg.org"
                        },
                        new
                        {
                            id = 34,
                            estado = true,
                            id_link_grp = 4,
                            nombre = "SocialSVG",
                            url_link = "https://www.svgrepo.com/collection/social-and-company-colored-logo-icons"
                        },
                        new
                        {
                            id = 35,
                            estado = true,
                            id_link_grp = 4,
                            nombre = "ConvertToIcon",
                            url_link = "https://convertio.co/es"
                        },
                        new
                        {
                            id = 36,
                            estado = true,
                            id_link_grp = 4,
                            nombre = "SoftIcons",
                            url_link = "https://www.softicons.com"
                        },
                        new
                        {
                            id = 37,
                            estado = true,
                            id_link_grp = 5,
                            nombre = "PlayCode",
                            url_link = "https://playcode.io"
                        },
                        new
                        {
                            id = 38,
                            estado = true,
                            id_link_grp = 5,
                            nombre = "GitHub",
                            url_link = "https://github.com/TheNefelin"
                        },
                        new
                        {
                            id = 39,
                            estado = true,
                            id_link_grp = 5,
                            nombre = "LinkedIn",
                            url_link = "https://www.linkedin.com/in/nefelin"
                        },
                        new
                        {
                            id = 40,
                            estado = true,
                            id_link_grp = 5,
                            nombre = "Figma",
                            url_link = "https://www.figma.com"
                        },
                        new
                        {
                            id = 41,
                            estado = true,
                            id_link_grp = 5,
                            nombre = "CodePen",
                            url_link = "https://codepen.io"
                        },
                        new
                        {
                            id = 42,
                            estado = true,
                            id_link_grp = 5,
                            nombre = "Canva",
                            url_link = "https://www.canva.com"
                        },
                        new
                        {
                            id = 43,
                            estado = true,
                            id_link_grp = 5,
                            nombre = "Songsterr",
                            url_link = "https://www.songsterr.com"
                        },
                        new
                        {
                            id = 44,
                            estado = true,
                            id_link_grp = 5,
                            nombre = "Mixamo",
                            url_link = "https://www.mixamo.com/#"
                        },
                        new
                        {
                            id = 45,
                            estado = true,
                            id_link_grp = 5,
                            nombre = "PublicAPI",
                            url_link = "https://publicapi.dev"
                        },
                        new
                        {
                            id = 46,
                            estado = true,
                            id_link_grp = 5,
                            nombre = "LabCenter",
                            url_link = "https://www.labcenter.com"
                        },
                        new
                        {
                            id = 47,
                            estado = true,
                            id_link_grp = 5,
                            nombre = "Oklch",
                            url_link = "https://oklch.com"
                        },
                        new
                        {
                            id = 48,
                            estado = true,
                            id_link_grp = 5,
                            nombre = "Excalidraw",
                            url_link = "https://excalidraw.com"
                        },
                        new
                        {
                            id = 49,
                            estado = true,
                            id_link_grp = 6,
                            nombre = "GoogleBard",
                            url_link = "https://bard.google.com"
                        },
                        new
                        {
                            id = 50,
                            estado = true,
                            id_link_grp = 6,
                            nombre = "ChatGPT",
                            url_link = "https://chat.openai.com"
                        },
                        new
                        {
                            id = 51,
                            estado = true,
                            id_link_grp = 6,
                            nombre = "Claude2",
                            url_link = "https://claude.ai"
                        },
                        new
                        {
                            id = 52,
                            estado = true,
                            id_link_grp = 6,
                            nombre = "LiterallyAnything",
                            url_link = "https://www.literallyanything.io"
                        },
                        new
                        {
                            id = 53,
                            estado = true,
                            id_link_grp = 6,
                            nombre = "BlackBox",
                            url_link = "https://www.useblackbox.io"
                        },
                        new
                        {
                            id = 54,
                            estado = true,
                            id_link_grp = 6,
                            nombre = "AgentGPT",
                            url_link = "https://agentgpt.reworkd.ai/es"
                        },
                        new
                        {
                            id = 55,
                            estado = true,
                            id_link_grp = 6,
                            nombre = "ElevenLabs",
                            url_link = "https://beta.elevenlabs.io"
                        },
                        new
                        {
                            id = 56,
                            estado = true,
                            id_link_grp = 6,
                            nombre = "Podcast",
                            url_link = "https://podcast.adobe.com/enhance"
                        },
                        new
                        {
                            id = 57,
                            estado = true,
                            id_link_grp = 6,
                            nombre = "Leonardo",
                            url_link = "https://leonardo.ai"
                        },
                        new
                        {
                            id = 58,
                            estado = true,
                            id_link_grp = 7,
                            nombre = "Jira",
                            url_link = "https://www.atlassian.com/es/software/jira"
                        },
                        new
                        {
                            id = 59,
                            estado = true,
                            id_link_grp = 7,
                            nombre = "Trello",
                            url_link = "https://trello.com/es"
                        },
                        new
                        {
                            id = 60,
                            estado = true,
                            id_link_grp = 7,
                            nombre = "ClickUp",
                            url_link = "https://clickup.com"
                        },
                        new
                        {
                            id = 61,
                            estado = true,
                            id_link_grp = 7,
                            nombre = "Asana",
                            url_link = "https://asana.com/es"
                        },
                        new
                        {
                            id = 62,
                            estado = true,
                            id_link_grp = 8,
                            nombre = "MiInsignia",
                            url_link = "https://www.acreditta.com/credential/63c99def-c48d-4495-aab5-00a3158d10a0"
                        },
                        new
                        {
                            id = 63,
                            estado = true,
                            id_link_grp = 8,
                            nombre = "GetOnbrd",
                            url_link = "https://www.getonbrd.com/misempleos"
                        },
                        new
                        {
                            id = 64,
                            estado = true,
                            id_link_grp = 8,
                            nombre = "Maps",
                            url_link = "https://geekflare.com/es/geocoding-maps-api-solution"
                        });
                });

            modelBuilder.Entity("db_portafolio.PF_Link_Grp", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<bool>("estado")
                        .HasColumnType("bit");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("id");

                    b.ToTable("pf_link_grp", (string)null);

                    b.HasData(
                        new
                        {
                            id = 1,
                            estado = true,
                            nombre = "Framework"
                        },
                        new
                        {
                            id = 2,
                            estado = true,
                            nombre = "Learning"
                        },
                        new
                        {
                            id = 3,
                            estado = true,
                            nombre = "Hosting"
                        },
                        new
                        {
                            id = 4,
                            estado = true,
                            nombre = "Images"
                        },
                        new
                        {
                            id = 5,
                            estado = true,
                            nombre = "Tools"
                        },
                        new
                        {
                            id = 6,
                            estado = true,
                            nombre = "IA"
                        },
                        new
                        {
                            id = 7,
                            estado = true,
                            nombre = "Agile"
                        },
                        new
                        {
                            id = 8,
                            estado = true,
                            nombre = "My Links"
                        });
                });

            modelBuilder.Entity("db_portafolio.PF_Pro_Lang", b =>
                {
                    b.Property<int>("id_project")
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    b.Property<int>("id_language")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.HasKey("id_project", "id_language");

                    b.HasIndex("id_language");

                    b.ToTable("pf_pro_lang", (string)null);

                    b.HasData(
                        new
                        {
                            id_project = 1,
                            id_language = 1
                        },
                        new
                        {
                            id_project = 1,
                            id_language = 2
                        },
                        new
                        {
                            id_project = 1,
                            id_language = 3
                        },
                        new
                        {
                            id_project = 1,
                            id_language = 4
                        },
                        new
                        {
                            id_project = 2,
                            id_language = 2
                        },
                        new
                        {
                            id_project = 2,
                            id_language = 3
                        },
                        new
                        {
                            id_project = 2,
                            id_language = 4
                        },
                        new
                        {
                            id_project = 3,
                            id_language = 2
                        },
                        new
                        {
                            id_project = 3,
                            id_language = 3
                        },
                        new
                        {
                            id_project = 3,
                            id_language = 4
                        },
                        new
                        {
                            id_project = 4,
                            id_language = 1
                        },
                        new
                        {
                            id_project = 4,
                            id_language = 2
                        },
                        new
                        {
                            id_project = 4,
                            id_language = 3
                        },
                        new
                        {
                            id_project = 4,
                            id_language = 4
                        },
                        new
                        {
                            id_project = 5,
                            id_language = 1
                        },
                        new
                        {
                            id_project = 6,
                            id_language = 5
                        },
                        new
                        {
                            id_project = 7,
                            id_language = 5
                        },
                        new
                        {
                            id_project = 8,
                            id_language = 2
                        },
                        new
                        {
                            id_project = 8,
                            id_language = 3
                        },
                        new
                        {
                            id_project = 8,
                            id_language = 4
                        },
                        new
                        {
                            id_project = 9,
                            id_language = 2
                        },
                        new
                        {
                            id_project = 9,
                            id_language = 3
                        },
                        new
                        {
                            id_project = 9,
                            id_language = 4
                        },
                        new
                        {
                            id_project = 10,
                            id_language = 2
                        },
                        new
                        {
                            id_project = 10,
                            id_language = 3
                        },
                        new
                        {
                            id_project = 10,
                            id_language = 4
                        },
                        new
                        {
                            id_project = 10,
                            id_language = 6
                        },
                        new
                        {
                            id_project = 11,
                            id_language = 1
                        },
                        new
                        {
                            id_project = 11,
                            id_language = 2
                        },
                        new
                        {
                            id_project = 11,
                            id_language = 3
                        },
                        new
                        {
                            id_project = 11,
                            id_language = 7
                        });
                });

            modelBuilder.Entity("db_portafolio.PF_Pro_Sour", b =>
                {
                    b.Property<int>("id_project")
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    b.Property<int>("id_source")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.HasKey("id_project", "id_source");

                    b.HasIndex("id_source");

                    b.ToTable("pf_pro_sour", (string)null);

                    b.HasData(
                        new
                        {
                            id_project = 1,
                            id_source = 1
                        },
                        new
                        {
                            id_project = 1,
                            id_source = 2
                        },
                        new
                        {
                            id_project = 2,
                            id_source = 3
                        },
                        new
                        {
                            id_project = 3,
                            id_source = 4
                        },
                        new
                        {
                            id_project = 4,
                            id_source = 5
                        },
                        new
                        {
                            id_project = 4,
                            id_source = 6
                        },
                        new
                        {
                            id_project = 5,
                            id_source = 7
                        },
                        new
                        {
                            id_project = 6,
                            id_source = 8
                        },
                        new
                        {
                            id_project = 7,
                            id_source = 9
                        },
                        new
                        {
                            id_project = 8,
                            id_source = 10
                        },
                        new
                        {
                            id_project = 8,
                            id_source = 11
                        },
                        new
                        {
                            id_project = 9,
                            id_source = 12
                        },
                        new
                        {
                            id_project = 10,
                            id_source = 13
                        },
                        new
                        {
                            id_project = 10,
                            id_source = 14
                        },
                        new
                        {
                            id_project = 11,
                            id_source = 15
                        },
                        new
                        {
                            id_project = 11,
                            id_source = 16
                        },
                        new
                        {
                            id_project = 11,
                            id_source = 6
                        },
                        new
                        {
                            id_project = 12,
                            id_source = 17
                        });
                });

            modelBuilder.Entity("db_portafolio.PF_Pro_Tech", b =>
                {
                    b.Property<int>("id_project")
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    b.Property<int>("id_technology")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.HasKey("id_project", "id_technology");

                    b.HasIndex("id_technology");

                    b.ToTable("pf_pro_tech", (string)null);

                    b.HasData(
                        new
                        {
                            id_project = 1,
                            id_technology = 2
                        },
                        new
                        {
                            id_project = 1,
                            id_technology = 7
                        },
                        new
                        {
                            id_project = 1,
                            id_technology = 9
                        },
                        new
                        {
                            id_project = 2,
                            id_technology = 9
                        },
                        new
                        {
                            id_project = 3,
                            id_technology = 9
                        },
                        new
                        {
                            id_project = 4,
                            id_technology = 2
                        },
                        new
                        {
                            id_project = 4,
                            id_technology = 7
                        },
                        new
                        {
                            id_project = 4,
                            id_technology = 9
                        },
                        new
                        {
                            id_project = 5,
                            id_technology = 8
                        },
                        new
                        {
                            id_project = 5,
                            id_technology = 10
                        },
                        new
                        {
                            id_project = 6,
                            id_technology = 2
                        },
                        new
                        {
                            id_project = 7,
                            id_technology = 2
                        },
                        new
                        {
                            id_project = 8,
                            id_technology = 5
                        },
                        new
                        {
                            id_project = 8,
                            id_technology = 12
                        },
                        new
                        {
                            id_project = 9,
                            id_technology = 5
                        },
                        new
                        {
                            id_project = 9,
                            id_technology = 6
                        },
                        new
                        {
                            id_project = 9,
                            id_technology = 11
                        },
                        new
                        {
                            id_project = 10,
                            id_technology = 11
                        },
                        new
                        {
                            id_project = 10,
                            id_technology = 7
                        },
                        new
                        {
                            id_project = 10,
                            id_technology = 9
                        },
                        new
                        {
                            id_project = 11,
                            id_technology = 7
                        },
                        new
                        {
                            id_project = 11,
                            id_technology = 10
                        },
                        new
                        {
                            id_project = 11,
                            id_technology = 11
                        });
                });

            modelBuilder.Entity("db_portafolio.PF_Project", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("orden")
                        .HasColumnType("int");

                    b.Property<string>("url_img")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("id");

                    b.ToTable("pf_project", (string)null);

                    b.HasData(
                        new
                        {
                            id = 1,
                            nombre = "Tecno Chile",
                            orden = 1,
                            url_img = "pf_tecno_chile.jpg"
                        },
                        new
                        {
                            id = 2,
                            nombre = "Web Components v1.0",
                            orden = 2,
                            url_img = "pf_web_components_v1.jpg"
                        },
                        new
                        {
                            id = 3,
                            nombre = "Kartax v1.0",
                            orden = 3,
                            url_img = "pf_kartax_v1.jpg"
                        },
                        new
                        {
                            id = 4,
                            nombre = "Portafolio V1.0",
                            orden = 4,
                            url_img = "pf_portafolio_v1.jpg"
                        },
                        new
                        {
                            id = 5,
                            nombre = "Game El Cubo v2.0",
                            orden = 5,
                            url_img = "pf_el_cubo_v2.jpg"
                        },
                        new
                        {
                            id = 6,
                            nombre = "Transbank POS Integration v1.0",
                            orden = 6,
                            url_img = "pf_transbank_pos.png"
                        },
                        new
                        {
                            id = 7,
                            nombre = "Arduino DHT Temperature Monitoring by Network",
                            orden = 7,
                            url_img = "pf_DHT.png"
                        },
                        new
                        {
                            id = 8,
                            nombre = "Kartax v2.0",
                            orden = 8,
                            url_img = "pf_kartax_v2.png"
                        },
                        new
                        {
                            id = 9,
                            nombre = "Portafolio v2.0",
                            orden = 9,
                            url_img = "pf_portafolio_v2.png"
                        },
                        new
                        {
                            id = 10,
                            nombre = "Kartax v3.0 (Developing...)",
                            orden = 10,
                            url_img = "pf_kartax_v3.png"
                        },
                        new
                        {
                            id = 11,
                            nombre = "Guides for games",
                            orden = 11,
                            url_img = "pf_guides_for_games.png"
                        },
                        new
                        {
                            id = 12,
                            nombre = "Aguiliza",
                            orden = 12,
                            url_img = "pf_guides_for_games.png"
                        });
                });

            modelBuilder.Entity("db_portafolio.PF_Source", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("url_deploy")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("url_repo")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("id");

                    b.ToTable("pf_pro_source", (string)null);

                    b.HasData(
                        new
                        {
                            id = 1,
                            nombre = "Tecno Chile v1.0 app",
                            url_deploy = "https://tecnochile.netlify.app",
                            url_repo = "https://github.com/TheNefelin/td_trabajo_grupal_03"
                        },
                        new
                        {
                            id = 2,
                            nombre = "Slifer api",
                            url_deploy = "https://slifer.bsite.net/index.html",
                            url_repo = "https://github.com/TheNefelin/td_api.NetCore6"
                        },
                        new
                        {
                            id = 3,
                            nombre = "Components v1.0 app",
                            url_deploy = "https://nefelin-components.netlify.app",
                            url_repo = "https://github.com/TheNefelin/my-web-components"
                        },
                        new
                        {
                            id = 4,
                            nombre = "Kartax v1.0 app",
                            url_deploy = "https://kartax.netlify.app",
                            url_repo = "https://github.com/TheNefelin/kartax-ant"
                        },
                        new
                        {
                            id = 5,
                            nombre = "Portafolio app",
                            url_deploy = "https://nefelin-portafolio.netlify.app",
                            url_repo = "https://github.com/TheNefelin/portafolio-site"
                        },
                        new
                        {
                            id = 6,
                            nombre = "Metalflap api",
                            url_deploy = "https://bsite.net/metalflap/index.html",
                            url_repo = "https://github.com/TheNefelin/portafolio_api.NETCore6"
                        },
                        new
                        {
                            id = 7,
                            nombre = "Download Link app",
                            url_deploy = "https://drive.google.com/drive/folders/1qttZk_iN8fHYVjHqI6_VLS4nyT4fTkyu?usp=drive_link"
                        },
                        new
                        {
                            id = 8,
                            nombre = "Transbank POS v1.0 app",
                            url_repo = "https://github.com/TheNefelin/Transbank-POS-v1"
                        },
                        new
                        {
                            id = 9,
                            nombre = "Arduino DHT Monitoring",
                            url_repo = "https://github.com/TheNefelin/DHT/tree/master/DHT"
                        },
                        new
                        {
                            id = 10,
                            nombre = "Kartax v2.0 app",
                            url_deploy = "https://kartax-express-production.up.railway.app/",
                            url_repo = "https://github.com/TheNefelin/kartax-express"
                        },
                        new
                        {
                            id = 11,
                            nombre = "Kartax v2.0 api",
                            url_deploy = "https://kartax-api-production.up.railway.app",
                            url_repo = "https://github.com/TheNefelin/kartax-api"
                        },
                        new
                        {
                            id = 12,
                            nombre = "Portafolio v2.0 app",
                            url_deploy = "http://www.francisco-dev.cl",
                            url_repo = "https://github.com/TheNefelin/portafolio-next13"
                        },
                        new
                        {
                            id = 13,
                            nombre = "Kartax v3.0 app",
                            url_deploy = "https://kartax-next13.vercel.app"
                        },
                        new
                        {
                            id = 14,
                            nombre = "Kartax v3.0 api",
                            url_deploy = "https://kartax-api-py.vercel.app/docs"
                        },
                        new
                        {
                            id = 15,
                            nombre = "Guia v1.0 app",
                            url_deploy = "https://guias-juegos-next13-ts.vercel.app",
                            url_repo = "https://github.com/TheNefelin/guias-juegos-next13-ts"
                        },
                        new
                        {
                            id = 16,
                            nombre = "SQL Server",
                            url_repo = "https://github.com/TheNefelin/SQLServer"
                        },
                        new
                        {
                            id = 17,
                            nombre = "Agiliza app",
                            url_deploy = "https://agiliza-next14-ts.vercel.app",
                            url_repo = "https://github.com/TheNefelin/agiliza-next14-ts"
                        });
                });

            modelBuilder.Entity("db_portafolio.PF_Technology", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("url_img")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("id");

                    b.ToTable("pf_pro_technology", (string)null);

                    b.HasData(
                        new
                        {
                            id = 1,
                            nombre = "Bootstrap",
                            url_img = "pf_bootstrap.svg"
                        },
                        new
                        {
                            id = 2,
                            nombre = "DotNet",
                            url_img = "pf_dotnet.svg"
                        },
                        new
                        {
                            id = 3,
                            nombre = "Git",
                            url_img = "pf_git.svg"
                        },
                        new
                        {
                            id = 4,
                            nombre = "MySQL",
                            url_img = "pf_mysql.svg"
                        },
                        new
                        {
                            id = 5,
                            nombre = "Node",
                            url_img = "pf_node.png"
                        },
                        new
                        {
                            id = 6,
                            nombre = "React",
                            url_img = "pf_react.svg"
                        },
                        new
                        {
                            id = 7,
                            nombre = "SqlServer",
                            url_img = "pf_mssql.png"
                        },
                        new
                        {
                            id = 8,
                            nombre = "Unity",
                            url_img = "pf_unity.png"
                        },
                        new
                        {
                            id = 9,
                            nombre = "VSCode",
                            url_img = "pf_vscode.png"
                        },
                        new
                        {
                            id = 10,
                            nombre = "VSStudio",
                            url_img = "pf_vsstudio.svg"
                        },
                        new
                        {
                            id = 11,
                            nombre = "NextJS",
                            url_img = "pf_nextjs.svg"
                        },
                        new
                        {
                            id = 12,
                            nombre = "PostgreSQL",
                            url_img = "pf_postgresql.png"
                        });
                });

            modelBuilder.Entity("db_portafolio.PF_Youtube", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("video_id")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("id");

                    b.ToTable("pf_youtube", (string)null);

                    b.HasData(
                        new
                        {
                            id = 1,
                            nombre = "Jam-Covid",
                            video_id = "0WsjRYgZMzs"
                        },
                        new
                        {
                            id = 2,
                            nombre = "Sky Lagoon",
                            video_id = "qUYQzlj_580"
                        },
                        new
                        {
                            id = 3,
                            nombre = "Valhalla",
                            video_id = "ktCw2CfWeTA"
                        },
                        new
                        {
                            id = 4,
                            nombre = "Yu-Gi-Oh",
                            video_id = "2q9liMSxOcE"
                        },
                        new
                        {
                            id = 5,
                            nombre = "Monster Hunter",
                            video_id = "yPKbPUM9RRc"
                        },
                        new
                        {
                            id = 6,
                            nombre = "Final Fantasy XV",
                            video_id = "3JlJ2fsOQnU"
                        });
                });

            modelBuilder.Entity("db_portafolio.PF_Link", b =>
                {
                    b.HasOne("db_portafolio.PF_Link_Grp", "LinkGrp")
                        .WithMany("Links")
                        .HasForeignKey("id_link_grp")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LinkGrp");
                });

            modelBuilder.Entity("db_portafolio.PF_Pro_Lang", b =>
                {
                    b.HasOne("db_portafolio.PF_Language", "Language")
                        .WithMany("ProjectLanguage")
                        .HasForeignKey("id_language")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("db_portafolio.PF_Project", "Project")
                        .WithMany("ProjectLanguage")
                        .HasForeignKey("id_project")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Language");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("db_portafolio.PF_Pro_Sour", b =>
                {
                    b.HasOne("db_portafolio.PF_Project", "Project")
                        .WithMany("ProjectSources")
                        .HasForeignKey("id_project")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("db_portafolio.PF_Source", "Source")
                        .WithMany("ProjectSources")
                        .HasForeignKey("id_source")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("Source");
                });

            modelBuilder.Entity("db_portafolio.PF_Pro_Tech", b =>
                {
                    b.HasOne("db_portafolio.PF_Project", "Project")
                        .WithMany("ProjectTechnology")
                        .HasForeignKey("id_project")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("db_portafolio.PF_Technology", "Technology")
                        .WithMany("ProjectTechnology")
                        .HasForeignKey("id_technology")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("Technology");
                });

            modelBuilder.Entity("db_portafolio.PF_Language", b =>
                {
                    b.Navigation("ProjectLanguage");
                });

            modelBuilder.Entity("db_portafolio.PF_Link_Grp", b =>
                {
                    b.Navigation("Links");
                });

            modelBuilder.Entity("db_portafolio.PF_Project", b =>
                {
                    b.Navigation("ProjectLanguage");

                    b.Navigation("ProjectSources");

                    b.Navigation("ProjectTechnology");
                });

            modelBuilder.Entity("db_portafolio.PF_Source", b =>
                {
                    b.Navigation("ProjectSources");
                });

            modelBuilder.Entity("db_portafolio.PF_Technology", b =>
                {
                    b.Navigation("ProjectTechnology");
                });
#pragma warning restore 612, 618
        }
    }
}
